oclif/plugin-plugins

- README.md
> Added clarifications to the behaviour of plugin:install and plugin:link

- package.json
see #86 
`^0.0.0` will only match `0.0.0`, and will not pick up the latest `@oclif/color` which is at `0.1.0`, that fixes an exception.
`0.x` will properly match all pre-release versions.
> fix: incorrect semver version for @oclif/color

- package.json
- src/plugins.ts
- test/commands/plugins/index.test.ts
- yarn.lock
Currently, if the registry returns anything that is not a 200 status
code this function returns `false`. In the case where we are trying to
check whether the package associated with a friendly name and the registry
returns a 503 this will result in fetching and installing
the wrong package.
i.e. Doing `heroku plugins:install api`
- Attempt to see if [`@heroku-cli/plugin-api`](https://www.npmjs.com/package/@heroku-cli/plugin-api) exists
- NPM returns 503
- Installs [`api`](https://www.npmjs.com/package/api)!!
In this case, this is fairly harmless as that particularly library
doesn't do much. However, it could be used maliciously!
I think it may be better to re-raise the initial error in this scenario if we
can't be sure that the package does not exist.
> feat: only return false on 404 in hasNpmPackage

- src/hooks/update.ts
> fix: hook fails silently on `yarn add` during update of plugins

- src/index.ts
Fixes https://github.com/oclif/plugin-plugins/issues/97
Recent updates to tslib no longer allow exporting * for defaults.
> fix: export the default plugins class

- README.md
- src/commands/plugins/install.ts
This pull request removes terms that are not inclusive.
> fix: use inclusive terms

- src/commands/plugins/install.ts
We store private repositories in git, and require support for installing plugins via that route. This adds support for those url's.
This is an enhancement on top of #74.
> Support git+ssh and .git urls

- src/commands/plugins/uninstall.ts
- src/plugins.ts
- test/commands/plugins/index.test.ts
Currently trying to uninstall a package using a tag name works for install but not uninstalling. The tag can be ignored and the uninstall should work with just the package name. This package has a oclif scope of `heroku-plugins` in the package.json which is why `./bin/run plugins:install apps` works in the tests.
```
./bin/run plugins:install apps
./bin/run plugins
./bin/run plugins:uninstall apps
./bin/run plugins:install @heroku-cli/plugin-apps
./bin/run plugins
./bin/run plugins:uninstall @heroku-cli/plugin-apps
./bin/run plugins:install @heroku-cli/plugin-apps@latest
./bin/run plugins
./bin/run plugins:uninstall @heroku-cli/plugin-apps@latest
./bin/run plugins:install salesforce-alm
./bin/run plugins
./bin/run plugins:uninstall salesforce-alm
```
```
Installing plugin apps... …
```
> fix: allow tagged packages to be uninstalled

- src/commands/plugins/inspect.ts
Adds `plugins:inspect` command:
```~/code/plugin-plugins [mdonnalley/inspect] : sfdx plugins:inspect --help
inspects an installed plugin
USAGE
$ sfdx plugins:inspect PLUGIN...
ARGUMENTS
PLUGIN  [default: .] plugin to inspect
OPTIONS
-h, --help     show CLI help
-v, --verbose
EXAMPLE
$ sfdx plugins:inspect myplugin
```
```
~ [] : sfdx plugins:inspect salesforcedx
salesforcedx
version: 51.0.2
tag: latest-rc
homepage: https://github.com/salesforcecli/salesforcedx
location: /Users/mdonnalley/.local/share/sfdx/node_modules/salesforcedx
commands:
force:lightning:lint
dependencies:
@salesforce/plugin-apex: 0.1.4
@salesforce/plugin-custom-metadata: 1.0.11
@salesforce/plugin-limits: 1.0.3
@salesforce/plugin-schema: 1.0.3
@salesforce/plugin-templates: 51.1.0
@salesforce/plugin-user: 1.1.0 …
```
> feat: add plugins:inspect

- src/plugins.ts
- test/commands/plugins/index.test.ts
Modify plugins.ts#hasPackage to use npm instead of https to check if a package exists on the registry.
https://github.com/oclif/plugin-plugins/issues/282
> fix: install should use npm to check registry

- src/commands/plugins/index.ts
- src/commands/plugins/inspect.ts
- src/commands/plugins/install.ts
- src/commands/plugins/link.ts
- src/commands/plugins/uninstall.ts
- src/commands/plugins/update.ts
- test/commands/plugins/index.test.ts
- yarn.lock
> fix: adjust help text to new style guide

- src/plugins.ts
Reverts https://github.com/oclif/plugin-plugins/pull/517
`oclif/core` now uses `ts-node` to compile linked TS plugins at runtime so this compile step in `plugins link` is no longer needed.
https://github.com/oclif/core/pull/650
[@W-12702335@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NKv6SYAT/view)
> fix: remove TS compile step for linked plugins

- .github/workflows/onPushToMain.yml
- .github/workflows/onRelease.yml
- CHANGELOG.md
- package.json
- src/plugins.ts
Fix `plugins:install` failing to install legacy (`cli-engine`, old heroku) plugins.
After moving to latest `oclif/core` and `plugin-plugins`, the heroku CLI started to fail when trying to install legacy plugins, probably caused by this code:
https://github.com/oclif/core/blob/a18803454449986e03549838ba3928c66f98da37/src/config/plugin.ts#L161-L165
`heroku` has `plugin-legacy` as a dependency to make legacy plugins work with latest oclif/core:
https://github.com/heroku/cli/blob/master/packages/cli/package.json#L39
init hook that does the plugin conversion at runtime:
https://github.com/oclif/plugin-legacy/blob/main/src/hooks/init.ts
This PR fixes the issue by checking if the plugin being installed was loaded by `plugin-legacy` as an instance of `PluginLegacy`.
> fix: handle legacy plugins

- package.json
- src/plugins.ts
- src/util.ts
- test/commands/plugins/index.test.ts
- yarn.lock
When installing a plugin using an "unfriendly" plugin name, `plugins install` needs to call npm to verify that the pkg exists in the registry. Until now it's been doing that by executing `npm show <pkg-name> dist-tags`, which works fine unless you don't have `npm` installed globally on your system.
This PR updates this check to use the `npm` version pinned in and shipped with `plugin-plugins`, this way the user doesn't need to install npm and also helps avoid weird issues if a user has an old npm version or a new breaking change is released.
1. Checkout this PR locally
2. Link plugin (`plugins link .`)
3. Try installing a plugin using an "unfriendly" name and verify the debug output to see which node/npm is being used.
**Suggestion**
set `DEBUG='@oclif/plugins'` when testing to see …
> fix: use internal npm for pkg checks

- package.json
- src/commands/plugins/install.ts
- yarn.lock
Fixes: https://github.com/oclif/plugin-plugins/issues/594
Use `validate-npm-package-name` to validate the plugin name is a valid npm pkg name before doing any initialization.
https://github.com/npm/validate-npm-package-name
@W-13099057@
> fix: validate plugin name before install

- .mocharc.json
- src/commands/plugins/index.ts
- test/commands/plugins/index.test.ts
- yarn.lock
add `--json` for `x plugins` command.
side effect
- significantly extends UT timeout limit for windows (this *should* unblock some of the dependabot PRs)
https://github.com/forcedotcom/cli/issues/267
@W-13472231@
QA: you can `plugins:link` this, but sometimes you'll end up in a broken state when uninstalling it and will need to re-install the CLI?
> feat: json output for plugins list

- .github/dependabot.yml
- .github/workflows/failureNotifications.yml
- .github/workflows/update-npm-version.yml
We have a customer needs the included `npm` version to be one that has (at some point) been bundled with node lts.
We will install the `npm` version that is included with the Github Action runner's LTS node
If there are changes, we will commit them to `main`. This will run weekly on Tuesdays, that way it will be included in Tuesday's `nightly` to be promoted to `latest-rc` on Wednesday
[@W-13848117@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13848117)
Issue: https://github.com/forcedotcom/cli/issues/2327
Related: https://github.com/salesforcecli/plugin-trust/pull/572
> Add npm update workflow

- src/plugins.ts
- src/yarn.ts
- Checks for `oclif.lock` to see if `yarn` should be rerun with the `--prod` flag
- Removes experimental feature introduced here: https://github.com/oclif/plugin-plugins/pull/638
@W-14010705@
> feat: check for renamed yarn.lock during install

- src/commands/plugins/index.ts
- src/commands/plugins/inspect.ts
- src/commands/plugins/install.ts
- test/commands/plugins/index.test.ts
- Adds hidden `--jit` flag to `plugins install` for installing JIT plugin with the version specified by root plugin
- Adds warning message when running `plugins inspect` on an uninstalled JIT plugin
- Updates `--json` output for `plugins` to include all plugins (previously it was just user installed and linked plugins). This is not a breaking change since all the properties on the old json are still available on the new
- Adds list of uninstalled JIT plugins to `plugins --core` human readable output
> feat: incorporate jit plugins

- src/yarn.ts
Allows us to use a network mutex for concurrent yarn instances. This is not any faster than `file:` but it does seem to reduce the mutex `ECOMPROMISED` errors. Could be beneficial in the future. 
[@W-14122700@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14122700)
QA: 
- Ran `SF_USE_NETWORK_MUTEX=true SFDX_NETWORK_MUTEX_PORT=31999 ../plugin-release-management/bin/run cli:install:jit:test`
- Inspected Network tab on activity monitor (notice custom port):
> Yarn network mutex

- src/commands/plugins/link.ts
- src/plugins.ts
Add `--[no-]install` flag to `plugins link`, which will bypass the `yarn install` step in the link process. This allows the command to run considerably faster in situations where you know you don't need to re-install dependencies, e.g. integration tests that run `plugins link` after having already run `yarn` on the plugin dir.
> feat: allow --no-install on plugins link

- package.json
- src/plugins.ts
- src/yarn.ts
- yarn.lock
- Add `HUSKY=0` env var during yarn executions to avoid husky failures
- Only compile plugin after install if it's ESM && `tsconfig.json` exists. 
use `nightly` sf since that will have the version of oclif/core that can auto-transpile CJS-github plugins 
- `sf plugins install oclif/version`, `sf version`
- `sf plugins install mdonnalley/plugin-dummy`, `sf hello world`
> fix: HUSKY=0 on github installs

- src/commands/plugins/reset.ts
Adds `plugins reset` cmd to remove all user-installed and linked plugins in parallel.
> feat: add plugins reset cmd

- src/plugins.ts
- test/integration/install.integration.ts
Fixes what appears to an oversight in https://github.com/oclif/plugin-plugins/pull/582.
Adds an integration test to avoid future issues.
> fix: allow installing legacy plugins if @oclif/plugin-legacy in plugins

- src/commands/plugins/install.ts
- src/util.ts
- Send all errors and warning messages in `YarnWarningCache` to stderr
- Use `this.log` in `plugins install` to log success message so that it can automatically be hidden when `--json` is present
@W-14457843@
> fix: all error and warnings to stderr, this.log in commands

- src/util.ts
Reported here:
https://github.com/forcedotcom/cli/issues/2564
plugin-plugins v4 will always perform a check to ensure a plugin exists in npm (`npm show <plugin> dist-tags`), since it uses the bundled npm instead of the global one it requires to call it using node (so it tries to get the path to node and path to npm-cli.js).
on plugin-plugins v3 this check would only happen if you tried to install a plugin and:
1) its name didn't include a `@`
2) root CLI didn't specify `pjson.oclif.scope
but `await this.npmHasPackage(unfriendly)` was always silently failing on windows (prob on mac/linux too) if the path to node contains spaces. 
https://github.com/oclif/plugin-plugins/blob/5ba86b5dd7d44a3cb317437055ea3db40318ced3/src/plugins.ts#L93
v4 made `npmHasPackage` thrown on not found: …
> fix: handle spaces in node bin path

- src/commands/plugins/install.ts
enables `--json` flag for plugins:install
@W-14457843@
[sf package version create --json not returning proper json output#2562](https://github.com/forcedotcom/cli/issues/2562)
> fix: enable --json for plugins install

- src/plugins.ts
- src/util.ts
Fixes: https://github.com/forcedotcom/cli/issues/2564
Follow-up from: https://github.com/oclif/plugin-plugins/pull/711
The fix in 711 worked on my windows box because:
1) tested with latest sf installed from npm
2) the path to my node bin has a space
`plugin-plugins` get the path to the npm-cli.js from the bundled one, which in my case it didn't contain a space in the path so only quoting the node bin path was enough.
When using a windows installer, both the node binary and npm-cli.js file come from the same CLI dir so both need to be double-quoted when passed to shelljs.exec.
@ W-14480077@
> fix: handle spaces in node/npm path

- src/util.ts
- test/utils.test.ts
- Scope `plugins install` warnings to the plugin being installed
- Handle `bugs` or `repository` being a string or object
> fix: scope install warnings to plugin being installed

- src/plugins.ts
Currently plugins that have never been publish to the npm registry (but have been published to a local or private registry) won't pass validation since `npm show` always runs against the npm public registry. This PR adds the `--registry` flag if the scoped `NPM_REGISTRY` env var exists.
> fix: respect scoped NPM_REGISTRY env var when running npm show

- src/commands/plugins/inspect.ts
Make `plugins inspect` dependency resolution deterministic by checking possible paths serially instead of in parallel
This should also fix flaky integration tests
> fix: make dep resolution deterministic

- src/commands/plugins/reset.ts
- src/plugins.ts
Adds `--reinstall` and `--hard` flags to `plugins reset`
`--reinstall` allows users to automatically reinstall every plugin that gets uninstalled
`--hard` will force remove all package manager related files (node_modules, package.json, yarn.lock, package-lock.json) from data directory (`~/.local/share/<CLI>`)
The goal is to provide users an easy way to get themselves into a clean state if something should go wrong in the upcoming transition from `yarn` to `npm` (https://github.com/oclif/plugin-plugins/pull/776)
https://github.com/oclif/plugin-plugins/assets/10244328/9f57f514-a727-4c19-97cb-14a2bce877fa
> feat: reset --reinstall --hard

- src/commands/plugins/reset.ts
Show url when reinstalling plugins during `plugins reset --reinstall`
> fix: display url when resetting plugin from url

- package.json
- src/fork.ts
- src/npm.ts
- src/plugins.ts
- src/yarn.ts
- yarn.lock
- Use `yarn` when installing deps during a `plugins link` of a plugin with a yarn.lock
- Skip install step of `plugins link` if a pnpm plugin
- Skip install step if no lock file (yarn, npm, or pnpm) is found
@W-15479725@
See https://github.com/forcedotcom/cli/issues/2818
> fix: use yarn to install deps when linking yarn plugins

- package.json
- src/commands/plugins/index.ts
- src/commands/plugins/inspect.ts
- yarn.lock
Use object-treeify directly instead of `ux.tree`. This should hopefully help some of the interoperability tests pass on https://github.com/oclif/core/pull/1056/
> fix: use object-treeify instead of ux

- .github/workflows/onRelease.yml
- .github/workflows/test.yml
- README.md
- package.json
- src/npm.ts
- src/plugins.ts
- src/spawn.ts
- src/yarn.ts
- yarn.lock
- Default to globally installed npm and yarn if they can't be found in plugin-plugin's node_modules
- Use spawn instead of fork
Fixes #864 
@W-15703207@
> feat: fall back to global npm and yarn if not found

- README.md
- package.json
- src/commands/plugins/index.ts
Remove the `config` property from json response on `plugins --json`
Fixes https://github.com/oclif/plugin-plugins/issues/876
@W-15839618@
> fix: remove config from json response

- package.json
- src/commands/plugins/index.ts
- src/commands/plugins/install.ts
- test/commands/plugins/index.test.ts
- test/commands/plugins/install.test.ts
- yarn.lock
- Remove root plugin from human readable output in `plugins --core` (still present in json)
- Disallow installing root plugin. It will error if it's the only plugin provided, otherwise it will warn
- Suggest that the user use `update` if the CLI is installable and plugin-update is installed
@W-14481853@
> feat: disallow installing root plugin

- src/commands/plugins/install.ts
- src/commands/plugins/uninstall.ts
This PR adds 2 new hooks:
`plugins:postinstall`: runs after `plugins install`
`plugins:postuninstall`: runs after `plugins uninstall`
Added for the autocomplete refresh-cache hook:
https://github.com/oclif/plugin-autocomplete/pull/753
See QA steps on the linked PR ⬆️ 
@W-12465784@
> feat: add `plugins:post`* hooks

- src/plugins.ts
When installing multiple plugins from a file url, plugins could get overwritten because the logic used to determine the package name always assumed that it was handling a git url
@W-18696886@
> fix(W-18696886): resolve package name when using file url
